# Deployment of Classification Codes Using NB

In [1]:
# Import libraries
import sklearn
import pandas as pd
import numpy as np
import warnings
import pickle

In [2]:
# Ignore warnings
warnings.filterwarnings("ignore")

In [3]:
load_model=pickle.load(open("Pythoncode_NB1.sav", "rb"))
Result1 = load_model.predict([[40,30000,1]])
Result1

array([0], dtype=int64)

In [4]:
load_model=pickle.load(open("Pythoncode_NB2.sav", "rb"))
Result1 = load_model.predict([[40,30000,1]])
Result1

array([0], dtype=int64)

In [9]:
load_model=pickle.load(open("Pythoncode_NB3.sav", "rb"))
Result1 = load_model.predict([[40,30000,1]])
Result1

array([0], dtype=int64)

In [11]:
load_model=pickle.load(open("Pythoncode_NB4.sav", "rb"))
Result1 = load_model.predict([[40,30000,1]])
Result1

array([0], dtype=int64)